In [1]:
import numpy as np

c = np.array([[1, 0, 0, 0, 0, 0, 0]]) # 入力
W = np.random.randn(7, 3)             # 重み
h = c @ W                             # 中間ノード
print(h)

[[ 1.56149016  0.20065069 -0.64284873]]


In [2]:
import sys
sys.path.append('..')
import numpy as np
from common.layers import MatMul

c = np.array([[1, 0, 0, 0, 0, 0, 0]])
W = np.random.randn(7, 3)
layer = MatMul(W)
h = layer.forward(c)
print(h)

[[-0.67801243  0.56433297 -0.85858589]]


In [3]:
import sys
sys.path.append('..')
from common.util import preprocess

text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)
print(corpus)
print(id_to_word)

[0 1 2 3 4 1 5 6]
{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


In [4]:
from common_util import create_contexts_target
contexts, target = create_contexts_target(corpus, window_size=1)

print(contexts)
print(target)

[[0 2]
 [1 3]
 [2 4]
 [3 1]
 [4 5]
 [1 6]]
[1 2 3 4 1 5]


In [7]:
import sys
sys.path.append('..')
from common.util import preprocess, create_contexts_target, convert_one_hot

text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)

contexts, target = create_contexts_target(corpus, window_size=1)

vocab_size = len(word_to_id)
target = convert_one_hot(target, vocab_size)
contexts = convert_one_hot(target, vocab_size)

print(target)
print(contexts)

[[0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0]]
[[[1 0 0 0 0 0 0]
  [0 1 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]]

 [[1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [0 1 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]]

 [[1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [0 1 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]]

 [[1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [0 1 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]]

 [[1 0 0 0 0 0 0]
  [0 1 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]]

 [[1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]
  [0 1 0 0 0 0 0]
  [1 0 0 0 0 0 0]]]
